### ISSUE TITLE
PA Review: New Account Creation/Login & Demo Account Login

### ISSUE THREAD

**Issue by TWSummer** [TWSummer/FriendFinder#2]
- [x] Create users table, User model validations, routes, and users and session controllers
- [x] Create ajax requests, actions, User and Errors Reducer, and add to store
- [x] Make AuthRoute for users to view homepage, and access login and signout forms
- [x] Allow users to log out
- [x] Display authentication errors
- [x] Add styling
- [x] Create profiles table, Profile model validations, add routes, and profiles controller
- [x] Add relations between users and profiles, validate that profile exists with appropriate defaults when registering user.
- [x] Create ajax requests, actions and profiles reducer, and add to store
- [x] Create profile components
- [x] Allow users to set location using Google Maps API
- [x] Display profile update errors
- [ ] Allow users to upload primary image to be stored on AWS

**Comment by TWSummer** [comment]
- [ ] Create Users table
- [ ] Add users model validations

**Comment by AAlfarho** [comment]
Assign this back to me after updating the wiki with a link to live app.

**Comment by AAlfarho** [comment]
Great job and progress for this MVP, only a couple of details before we can move forward.

## Functionality
- [ ] Implement a demo login.
- [ ] Have a default route in your switch on the LoggedIn component, that way we can handle cases when users try to access non-existing pages, for example: `https://make-friends.herokuapp.com/#/this-does-not-exist` should probably redirect to home if logged in. I would *strongly* suggest for you to rename your components name, `LoggedIn` does not bring any light in what the component is supposed to represent in term of components.
- [ ] The profile makes use of what looks like modals, from a UX point of view, users should be able to close the _modal_ by either clicking `esc` or clicking on the dim area. Also, consider autofocusing the input field.
- [ ] Set a default _missing image_ for newly created accounts.


## Styling
- [ ] Consider the following snap for the errors form. Currently when errors are rendered the input tags are smaller than the parent div.
![screen shot 2018-02-02 at 12 02 07 pm](https://user-images.githubusercontent.com/1103663/35752464-f3fcfa4e-0810-11e8-99ef-60328a68829e.png)
- [ ] Consider having your profile update form as a modal, if not, set the background color of the form to something with more contrast. Set the same padding to all the components of the form, something along the lines of the following snap
![screen shot 2018-02-02 at 1 51 49 pm](https://user-images.githubusercontent.com/1103663/35756459-424aa2d2-0820-11e8-8a2a-61d285cf539c.png)


Once these updates are pushed to Heroku, assign this issue back to me.

**Comment by AAlfarho** [comment]
Great job on the updates,
on the profile editing section, set the `width` of the _update_  button to the same width as the inputs ( first name, location & map).
<img width="373" alt="screen shot 2018-02-05 at 2 37 33 pm" src="https://user-images.githubusercontent.com/1103663/35832437-28e67708-0a82-11e8-9527-aa82f78aff7c.png">

This MVP is now complete.
