### ISSUE TITLE
PA Review: Compatibility Questions

### ISSUE THREAD

**Issue by TWSummer** [TWSummer/FriendFinder#3]
- [x] Create questions, question_options, question_answers, and question_friend_answers tables
- [x] Set up models, relationships, and validations
- [x] Create routes to get a question and post an answer and corresponding controller methods
- [x] Seed database with questions and question_options
- [x] Create Question Component
- [x] Add styling

**Comment by AAlfarho** [comment]
Great job on the implementation of this MVP. 
Amazing seeding, 52 questions will give the site a more complete feeling.
Styling looks great, the box-shadowing of the questions gives the whole form some depth. Incredible attention to detail in the color highlighting of the _importance_ input, kudos!

## Functionality
- [ ] (Optional) When checking the radio button `Any of the above`, previous selections are unchecked, that's a great UX principle. With that in mind if, after that, if I changed my mind and I want to select an _ideal answer_ I have to uncheck the `Any of the above`, that means 2 clicks to select my desired answer.

## Styling
- [ ] (Optional) When going from `/#/friends` to `/#/questions`, for a split second we can see the `Compatibility Questions` empty form, it'd be great to have a spinner here.

This MVP is complete. The above feedback is optional, but I strongly suggest keeping track on it by creating new issues and tag them as enhancements.

Great job!
