### ISSUE TITLE
PA Review: Browse and Search other users by location, age, last sign in

### ISSUE THREAD

**Issue by TWSummer** [TWSummer/FriendFinder#4]
- [x] Create search table, model, controller, & view
- [x] Set up a search with default parameters whenever a new user is created.
- [x] Create search header component to display and update search parameters
- [x] Create search display components so users can see search results
- [x] Create components to view a profile that belongs to another user

**Comment by AAlfarho** [comment]
Good job on the implementation of the feature, the core feature works great. There are a couple of details that we need to lock down before closing this MVP.

## Functionality
- [ ] Creating a new user and visiting the profile `/#/profile/` is breaking now.
- [ ] There is an issue with the data on _Justin Biebers_ profile, and the display of Roger Federer's profile.
- [ ] Be consistent with the seeding, Richard Dawkins being a small town girl, might not be the best _about_ note, unless it is an inside joke?

## Style
- [ ] Reconsider your _search_  settings to a `drop-down` menu. Having a whole modal for a single input takes the focus away from the app main concern, making friends, and does not flow with the rest of the app. Something along the following lines.
![screen shot 2018-02-08 at 9 38 13 am](https://user-images.githubusercontent.com/1103663/35988683-02caa682-0cb4-11e8-87a3-2e8e4a32c549.png)
- [ ] On the initial screen, `footer`. Center your elements, and keep casing consistent, your `email` is all in lowercase.

**Comment by AAlfarho** [comment]
Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by AAlfarho** [comment]
MVP is almost complete.

If we are opting for the modal type browse settings which I am still opposed to, let's update the components and center the items inside of them. Hitting `esc` is not working for the `anywhere` setting.
