### ISSUE TITLE
PA Review: Match Percentages based on question answers

### ISSUE THREAD

**Issue by TWSummer** [TWSummer/FriendFinder#5]
- [x] Friend search requests should include question answers and question friend answers (to avoid N+1 query)
- [x] Calculate compatibility percentage from answers
- [x] Weight percentages according to importance indicated by users when answering questions
- [x] Send calculated percentages when user is searching friends or viewing another profile
- [x] Display compatibility percentages on friend search page and profile view
- [x] Allow friend searches to be sorted by compatibility percentage or distance

**Comment by AAlfarho** [comment]
Great job with this feature. Allowing for users to match via their questions is almost complete,
just a minor detail.

- [ ] Don't display 0% matched users.

**Comment by AAlfarho** [comment]
Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by TWSummer** [comment]
I'm not sure this is a good idea since then users who have created a new account will not be able to see anyone until they have answered some questions.

**Comment by AAlfarho** [comment]
The more reason to do so, OkCupid forces you to answer the questionaries (onboarding) before being able to do anything on the site.

This decision is all up to you.
