### ISSUE TITLE
PA Review: Messaging

### ISSUE THREAD

**Issue by TWSummer** [TWSummer/FriendFinder#6]
- [x] Create messages table, model, controller, and views
- [x] Create messages util, actions, and reducer
- [x] Have messages container sort messages into conversations for the index to display
- [x] Create message index and message index item components

**Comment by AAlfarho** [comment]
Great job on the display and filter of the messages!

As an MVP this feature is now complete, I would still suggest checking out ActionCable for websockets, that way we won't need to refresh the page to get new messages.
